maps/urls.py
from django.urls import path
from maps import views

urlpatterns = [
    path('', views.GlobalMapView.as_view(), name='global_map'),
    path('ajax-upload-placemarks/',
         views.AjaxUploadPlacemarks.as_view(),
         name='ajax_get_geo_objects_placemark'),
]

meetup_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('meetup/', include('meetups.urls')),
    path('search/', include('search.urls')),
    path('schedule/', include('schedule.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('auth/', include('users.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('djeym/', include('djeym.urls', namespace='djeym')),
    path('map/', include('maps.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'homepage.views.error_404_view'
handler500 = 'homepage.views.error_500_view'

schedule/urls.py
from django.urls import path
from schedule import views

app_name = 'schedule'

urlpatterns = [
    path('<int:event_id>/', views.ScheduleView.as_view(), name='meetup-detail'),
    path('', views.ScheduleView.as_view(), name='schedule'),
]

schedule/models.py
# from django.db import models

# Create your models here.

schedule/views.py
import datetime
import calendar
from django.views.generic import ListView
from meetups.models import Meetup

from schedule.utils import Calendar


class ScheduleView(ListView):
    model = Meetup
    template_name = 'schedule/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar or get it from the url
        # returns error message if date does not exist
        try:
            date = get_date(self.request.GET.get('month', None))
        except Exception:
            context['date_error'] = '<h1>Такай даты не существует 🥶</h1>'
            return context

        self.request.GET._mutable = True
        self.request.GET.pop('month', None)
        query = self.request.GET

        # Instantiate our calendar class with today's year and date
        cal = Calendar(date.year, date.month, user=self.request.user)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(query, withyear=True)
        context['calendar'] = html_cal
        context['prev_month'] = prev_month(date, query)
        context['next_month'] = next_month(date, query)

        return context


def get_date(cur_month):
    if not cur_month:
        return datetime.datetime.today()

    if cur_month.count('-') == 2:
        return datetime.datetime.strptime(cur_month, '%Y-%m-%d')
    else:
        return datetime.datetime.strptime(cur_month, '%Y-%m')


def prev_month(date, query):
    first = date.replace(day=1)
    month = first - datetime.timedelta(days=1)
    data = f'month={month.year}-{month.month}&{query.urlencode()}'
    return data


def next_month(date, query):
    days_in_month = calendar.monthrange(date.year, date.month)[1]
    last = date.replace(day=days_in_month)
    month = last + datetime.timedelta(days=1)
    data = f'month={month.year}-{month.month}&{query.urlencode()}'
    return data

templates/schedule/index.html
{% extends 'includes/index.html' %}

{% load static %}

{% block title %}
    Календарь
{% endblock %}

{% block main %}
    <section class="container">
        {% if date_error %}
            {{ date_error }}
        {% else %}
            <div class="clearfix">
                <a class="btn btn-info left" href="{% url 'schedule:schedule' %}?{{ prev_month }}"> Предыдущий месяц </a>
                <a class="btn btn-info right" href="{% url 'schedule:schedule' %}?{{ next_month }}"> Следующий месяц </a>
            </div>
            {{ calendar|safe }}
        {% endif %}
    </section>
{% endblock %}

{% block css %}
    <link href="{% static 'css/calendar.css' %}" rel="stylesheet">
{% endblock %}

{% block js %}
    <script src="{% static 'js/slim.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script>
        $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip({html: true});
        });
    </script>
{% endblock %}